//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tol.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class LINK_ITEM_FILTER
    {
        public int ID_LINK { get; set; }
        public int ID_ITEM { get; set; }
        public int ID_FILTER { get; set; }
    
        public virtual ITEM ITEM { get; set; }
        public virtual FILTER FILTER { get; set; }
    }
}
