//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tol.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class BUBBLE
    {
        public int ID_BUBBLE { get; set; }
        public decimal SIZE { get; set; }
        public int ID_PROFIL { get; set; }
        public int ID_FILTER { get; set; }
        public int ID_TIME { get; set; }
    
        public virtual PROFIL PROFIL { get; set; }
        public virtual TIME TIME { get; set; }
        public virtual FILTER FILTER { get; set; }
    }
}
