//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tol.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ITEM()
        {
            this.LINK_ITEM_FILTER = new HashSet<LINK_ITEM_FILTER>();
        }
    
        public int ID_ITEM { get; set; }
        public string TITEL { get; set; }
        public string BODY { get; set; }
        public string PICTURE_URL { get; set; }
        public Nullable<int> ID_ARTICLE_TEMP { get; set; }
        public Nullable<int> ID_TIERS_TEMP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LINK_ITEM_FILTER> LINK_ITEM_FILTER { get; set; }
    }
}
